name: PR prechecks

on:
  pull_request:
    branches:
      - main

jobs:
  prechecks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      repository-projects: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
    
      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

    #   - name: Test code
    #     run: npm test