name: Publish VS Code Extension

on:
  push:
    branches:
      - main
#   release:
#     types: [published]
#   workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Package extension
        run: npx vsce package

      - name: Exctract version from package.json
        id: version
        run: |
          export PACKAGE_VERSION=$(grep '"version"' package.json | sed -E 's/.*"version": "([^"]+)".*/\1/')
          echo "PACKAGE_VERSION=$PACKAGE_VERSION"
          echo "::set-output name=package_version::$PACKAGE_VERSION"

      - name: Upload VSIX file as a release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./publink-${{ steps.version.outputs.package_version }}.vsix
          asset_name: publink-${{ steps.version.outputs.package_version }}.vsix
          asset_content_type: application/octet-stream

      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.AZURE_PAT }}
        run: npx vsce publish
